// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BookingSpecTests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("AccommodationSearch")]
    public partial class AccommodationSearchFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AccommodationSearch.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "AccommodationSearch", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Input valid data in order to Search accommodation on main page")]
        public virtual void InputValidDataInOrderToSearchAccommodationOnMainPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Input valid data in order to Search accommodation on main page", ((string[])(null)));
#line 3
this.ScenarioSetup(scenarioInfo);
#line 4
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 5
 testRunner.And("I navigate to url \"https://booking.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 6
 testRunner.When("I input data \"New York, New York State, USA\" in Destination Search field on main " +
                    "page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 7
 testRunner.And("I click on first autocomplete option that contains \"New York\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.And("I set the calendar for the current date plus one year", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.Then("I click button Search on main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 10
 testRunner.And("I see that I am on Search Result page and see that offered accommodation is in \"N" +
                    "ew York\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Input invalid data in accommodation search calendar on main page")]
        public virtual void InputInvalidDataInAccommodationSearchCalendarOnMainPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Input invalid data in accommodation search calendar on main page", ((string[])(null)));
#line 12
this.ScenarioSetup(scenarioInfo);
#line 13
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 14
 testRunner.And("I navigate to url \"https://booking.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Month",
                        "MonthDay",
                        "Year"});
            table1.AddRow(new string[] {
                        "Check In",
                        "04",
                        "15",
                        "2018"});
            table1.AddRow(new string[] {
                        "Check Out",
                        "04",
                        "15",
                        "2020"});
#line 15
 testRunner.When("I set following parameters in calendar on main page", ((string)(null)), table1, "When ");
#line 19
 testRunner.When("I input data \"Issaquah, WA, United States\" in Destination Search field on main pa" +
                    "ge", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
 testRunner.And("I click on first autocomplete option that contains \"Issaquah\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
 testRunner.Then("I click button Search on main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 22
 testRunner.And("I see date error message \"Reservations longer than 30 nights are not possible.\" o" +
                    "n main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Input invalid data in Destination Search accommodation field on main page")]
        public virtual void InputInvalidDataInDestinationSearchAccommodationFieldOnMainPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Input invalid data in Destination Search accommodation field on main page", ((string[])(null)));
#line 24
 this.ScenarioSetup(scenarioInfo);
#line 25
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 26
 testRunner.And("I navigate to url \"https://booking.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.When("I input data \"sfsadfasdf\" in Destination Search field on main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 28
 testRunner.Then("I click button Search on main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 29
 testRunner.And("I wait browser page to load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.And("I see destination error message \"Sorry, we don\'t recognize that name.\" on main pa" +
                    "ge", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Check that check-in date always earlier than check-out date")]
        [NUnit.Framework.TestCaseAttribute("04", "25", "2018", "04", "15", "2018", null)]
        [NUnit.Framework.TestCaseAttribute("04", "15", "2018", "04", "13", "2018", null)]
        public virtual void CheckThatCheck_InDateAlwaysEarlierThanCheck_OutDate(string monthIn, string monthDayIn, string yearIn, string monthOut, string monthDayOut, string yearOut, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check that check-in date always earlier than check-out date", exampleTags);
#line 32
this.ScenarioSetup(scenarioInfo);
#line 33
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 34
 testRunner.And("I navigate to url \"https://booking.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Month",
                        "MonthDay",
                        "Year"});
            table2.AddRow(new string[] {
                        "Check In",
                        string.Format("{0}", monthIn),
                        string.Format("{0}", monthDayIn),
                        string.Format("{0}", yearIn)});
            table2.AddRow(new string[] {
                        "Check Out",
                        string.Format("{0}", monthOut),
                        string.Format("{0}", monthDayOut),
                        string.Format("{0}", yearOut)});
#line 35
 testRunner.And("I set following parameters in calendar on main page", ((string)(null)), table2, "And ");
#line 39
 testRunner.Then("I make sure that check-out date is later for one day than check-in", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Check that Search accommodation Adults dropdown menu works properly")]
        public virtual void CheckThatSearchAccommodationAdultsDropdownMenuWorksProperly()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check that Search accommodation Adults dropdown menu works properly", ((string[])(null)));
#line 46
this.ScenarioSetup(scenarioInfo);
#line 47
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 48
 testRunner.And("I navigate to url \"https://booking.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
 testRunner.When("I input data \"Issaquah, WA, United States\" in Destination Search field on main pa" +
                    "ge", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 50
 testRunner.And("I click on first autocomplete option that contains \"Issaquah\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
 testRunner.And("I set the calendar for the current date plus one year", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table3.AddRow(new string[] {
                        "Adults",
                        "5"});
#line 52
 testRunner.When("I set following parameters in dropdown menus", ((string)(null)), table3, "When ");
#line 55
 testRunner.Then("I click button Search on main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 56
 testRunner.And("I see that Search result is for \"Groups\" and \"5 adults\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Check that Search accommodation Children dropdown menu works properly")]
        public virtual void CheckThatSearchAccommodationChildrenDropdownMenuWorksProperly()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check that Search accommodation Children dropdown menu works properly", ((string[])(null)));
#line 58
 this.ScenarioSetup(scenarioInfo);
#line 59
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 60
 testRunner.And("I navigate to url \"https://booking.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 61
 testRunner.When("I input data \"Issaquah, WA, United States\" in Destination Search field on main pa" +
                    "ge", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 62
 testRunner.And("I click on first autocomplete option that contains \"Issaquah\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 63
 testRunner.And("I set the calendar for the current date plus one year", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table4.AddRow(new string[] {
                        "Children",
                        "1"});
#line 64
 testRunner.When("I set following parameters in dropdown menus", ((string)(null)), table4, "When ");
#line 67
 testRunner.Then("I click button Search on main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 68
 testRunner.And("I see that Search result is for \"Families\" and \"1 child\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Check that Search accommodation Rooms dropdown menu works properly")]
        public virtual void CheckThatSearchAccommodationRoomsDropdownMenuWorksProperly()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check that Search accommodation Rooms dropdown menu works properly", ((string[])(null)));
#line 70
 this.ScenarioSetup(scenarioInfo);
#line 71
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 72
 testRunner.And("I navigate to url \"https://booking.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 73
 testRunner.When("I input data \"Issaquah, WA, United States\" in Destination Search field on main pa" +
                    "ge", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 74
 testRunner.And("I click on first autocomplete option that contains \"Issaquah\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 75
 testRunner.And("I set the calendar for the current date plus one year", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table5.AddRow(new string[] {
                        "Adults",
                        "5"});
            table5.AddRow(new string[] {
                        "Rooms",
                        "3"});
#line 76
 testRunner.When("I set following parameters in dropdown menus", ((string)(null)), table5, "When ");
#line 80
 testRunner.Then("I click button Search on main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 81
 testRunner.And("I see that Search result contains offers with \"3\" rooms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Check that Search accommodation option Buisness traveling works properly")]
        public virtual void CheckThatSearchAccommodationOptionBuisnessTravelingWorksProperly()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check that Search accommodation option Buisness traveling works properly", ((string[])(null)));
#line 83
this.ScenarioSetup(scenarioInfo);
#line 84
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 85
 testRunner.And("I navigate to url \"https://booking.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 86
 testRunner.When("I input data \"Issaquah, WA, United States\" in Destination Search field on main pa" +
                    "ge", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 87
 testRunner.And("I click on first autocomplete option that contains \"Issaquah\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 88
 testRunner.And("I set the calendar for the current date plus one year", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 89
 testRunner.When("I click Yes for Buisness traveling on main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table6.AddRow(new string[] {
                        "Adults",
                        "3"});
#line 90
 testRunner.When("I set following parameters in dropdown menus", ((string)(null)), table6, "When ");
#line 93
 testRunner.Then("I click button Search on main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 94
 testRunner.And("I see that Search result is for \"Business Travelers\" and \"3 adults\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Assurance that each checkbox filter of Accommodation search works properly")]
        public virtual void AssuranceThatEachCheckboxFilterOfAccommodationSearchWorksProperly()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Assurance that each checkbox filter of Accommodation search works properly", ((string[])(null)));
#line 96
this.ScenarioSetup(scenarioInfo);
#line 97
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 98
 testRunner.And("I navigate to url \"https://booking.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 99
 testRunner.And("I set my currency as \"U.S. Dollar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 100
 testRunner.When("I input data \"New York, New York State, USA\" in Destination Search field on main " +
                    "page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 101
 testRunner.And("I click on first autocomplete option that contains \"New York\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 102
 testRunner.And("I set the calendar for the current date plus one year", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 103
 testRunner.Then("I click button Search on main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 104
 testRunner.And("I wait browser page to load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table7.AddRow(new string[] {
                        "US$120 - US$180 per night",
                        "amount",
                        "On"});
#line 105
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table7, "And ");
#line 108
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table8.AddRow(new string[] {
                        "US$120 - US$180 per night",
                        "Off"});
#line 109
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table8, "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table9.AddRow(new string[] {
                        "US$180 - US$240 per night",
                        "amount",
                        "On"});
#line 112
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table9, "And ");
#line 115
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table10.AddRow(new string[] {
                        "US$180 - US$240 per night",
                        "Off"});
#line 116
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table10, "And ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table11.AddRow(new string[] {
                        "US$240 + per night",
                        "amount",
                        "On"});
#line 119
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table11, "And ");
#line 122
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table12.AddRow(new string[] {
                        "US$240 + per night",
                        "Off"});
#line 123
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table12, "And ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table13.AddRow(new string[] {
                        "Wonderful: 9+",
                        "amount",
                        "On"});
#line 126
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table13, "And ");
#line 129
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table14.AddRow(new string[] {
                        "Wonderful: 9+",
                        "Off"});
#line 130
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table14, "And ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table15.AddRow(new string[] {
                        "Very Good: 8+",
                        "amount",
                        "On"});
#line 133
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table15, "And ");
#line 136
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table16.AddRow(new string[] {
                        "Very Good: 8+",
                        "Off"});
#line 137
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table16, "And ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table17.AddRow(new string[] {
                        "Good: 7+",
                        "amount",
                        "On"});
#line 140
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table17, "And ");
#line 143
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table18.AddRow(new string[] {
                        "Good: 7+",
                        "Off"});
#line 144
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table18, "And ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table19.AddRow(new string[] {
                        "Pleasant: 6+",
                        "amount",
                        "On"});
#line 147
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table19, "And ");
#line 150
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table20.AddRow(new string[] {
                        "Pleasant: 6+",
                        "Off"});
#line 151
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table20, "And ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table21.AddRow(new string[] {
                        "1 star",
                        "amount",
                        "On"});
#line 154
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table21, "And ");
#line 157
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table22.AddRow(new string[] {
                        "1 star",
                        "Off"});
#line 158
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table22, "And ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table23.AddRow(new string[] {
                        "2 stars",
                        "amount",
                        "On"});
#line 161
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table23, "And ");
#line 164
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table24.AddRow(new string[] {
                        "2 stars",
                        "Off"});
#line 165
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table24, "And ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table25.AddRow(new string[] {
                        "3 stars",
                        "amount",
                        "On"});
#line 168
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table25, "And ");
#line 171
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table26.AddRow(new string[] {
                        "3 stars",
                        "Off"});
#line 172
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table26, "And ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table27.AddRow(new string[] {
                        "4 stars",
                        "amount",
                        "On"});
#line 175
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table27, "And ");
#line 178
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table28.AddRow(new string[] {
                        "4 stars",
                        "Off"});
#line 179
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table28, "And ");
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table29.AddRow(new string[] {
                        "5 stars",
                        "amount",
                        "On"});
#line 182
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table29, "And ");
#line 185
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table30.AddRow(new string[] {
                        "5 stars",
                        "Off"});
#line 186
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table30, "And ");
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table31.AddRow(new string[] {
                        "Unrated",
                        "amount",
                        "On"});
#line 189
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table31, "And ");
#line 192
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table32.AddRow(new string[] {
                        "Unrated",
                        "Off"});
#line 193
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table32, "And ");
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table33.AddRow(new string[] {
                        "Front Desk Open 24/7",
                        "amount",
                        "On"});
#line 196
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table33, "And ");
#line 199
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table34.AddRow(new string[] {
                        "Front Desk Open 24/7",
                        "Off"});
#line 200
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table34, "And ");
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table35.AddRow(new string[] {
                        "Hotels",
                        "amount",
                        "On"});
#line 203
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table35, "And ");
#line 206
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table36.AddRow(new string[] {
                        "Hotels",
                        "Off"});
#line 207
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table36, "And ");
#line hidden
            TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table37.AddRow(new string[] {
                        "Vacation Homes",
                        "amount",
                        "On"});
#line 210
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table37, "And ");
#line 213
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table38.AddRow(new string[] {
                        "Vacation Homes",
                        "Off"});
#line 214
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table38, "And ");
#line hidden
            TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table39.AddRow(new string[] {
                        "Hostels",
                        "amount",
                        "On"});
#line 217
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table39, "And ");
#line 220
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table40.AddRow(new string[] {
                        "Hostels",
                        "Off"});
#line 221
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table40, "And ");
#line hidden
            TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table41.AddRow(new string[] {
                        "Fitness Center",
                        "amount",
                        "On"});
#line 224
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table41, "And ");
#line 227
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table42.AddRow(new string[] {
                        "Fitness Center",
                        "Off"});
#line 228
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table42, "And ");
#line hidden
            TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table43.AddRow(new string[] {
                        "Massage",
                        "amount",
                        "On"});
#line 231
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table43, "And ");
#line 234
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table44 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table44.AddRow(new string[] {
                        "Massage",
                        "Off"});
#line 235
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table44, "And ");
#line hidden
            TechTalk.SpecFlow.Table table45 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table45.AddRow(new string[] {
                        "Fitness",
                        "amount",
                        "On"});
#line 238
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table45, "And ");
#line 241
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table46 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table46.AddRow(new string[] {
                        "Fitness",
                        "Off"});
#line 242
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table46, "And ");
#line hidden
            TechTalk.SpecFlow.Table table47 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table47.AddRow(new string[] {
                        "Great Value Today",
                        "amount",
                        "On"});
#line 245
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table47, "And ");
#line 248
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table48 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table48.AddRow(new string[] {
                        "Great Value Today",
                        "Off"});
#line 249
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table48, "And ");
#line hidden
            TechTalk.SpecFlow.Table table49 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table49.AddRow(new string[] {
                        "Kitchen facilities",
                        "amount",
                        "On"});
#line 252
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table49, "And ");
#line 255
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table50 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table50.AddRow(new string[] {
                        "Kitchen facilities",
                        "Off"});
#line 256
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table50, "And ");
#line hidden
            TechTalk.SpecFlow.Table table51 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table51.AddRow(new string[] {
                        "Empire State Building",
                        "amount",
                        "On"});
#line 259
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table51, "And ");
#line 262
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table52 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table52.AddRow(new string[] {
                        "Empire State Building",
                        "Off"});
#line 263
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table52, "And ");
#line hidden
            TechTalk.SpecFlow.Table table53 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table53.AddRow(new string[] {
                        "Times Square",
                        "amount",
                        "On"});
#line 266
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table53, "And ");
#line 269
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table54 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table54.AddRow(new string[] {
                        "Times Square",
                        "Off"});
#line 270
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table54, "And ");
#line hidden
            TechTalk.SpecFlow.Table table55 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table55.AddRow(new string[] {
                        "Brooklyn Bridge",
                        "amount",
                        "On"});
#line 273
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table55, "And ");
#line 276
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table56 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table56.AddRow(new string[] {
                        "Brooklyn Bridge",
                        "Off"});
#line 277
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table56, "And ");
#line hidden
            TechTalk.SpecFlow.Table table57 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table57.AddRow(new string[] {
                        "Central Park",
                        "amount",
                        "On"});
#line 280
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table57, "And ");
#line 283
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table58 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table58.AddRow(new string[] {
                        "Central Park",
                        "Off"});
#line 284
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table58, "And ");
#line hidden
            TechTalk.SpecFlow.Table table59 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table59.AddRow(new string[] {
                        "Top of the Rock",
                        "amount",
                        "On"});
#line 287
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table59, "And ");
#line 290
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table60 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table60.AddRow(new string[] {
                        "Top of the Rock",
                        "Off"});
#line 291
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table60, "And ");
#line hidden
            TechTalk.SpecFlow.Table table61 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table61.AddRow(new string[] {
                        "Family Rooms",
                        "amount",
                        "On"});
#line 294
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table61, "And ");
#line 297
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table62 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table62.AddRow(new string[] {
                        "Family Rooms",
                        "Off"});
#line 298
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table62, "And ");
#line hidden
            TechTalk.SpecFlow.Table table63 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table63.AddRow(new string[] {
                        "Pet Friendly",
                        "amount",
                        "On"});
#line 301
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table63, "And ");
#line 304
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table64 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table64.AddRow(new string[] {
                        "Pet Friendly",
                        "Off"});
#line 305
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table64, "And ");
#line hidden
            TechTalk.SpecFlow.Table table65 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table65.AddRow(new string[] {
                        "Facilities for Disabled Guests",
                        "amount",
                        "On"});
#line 308
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table65, "And ");
#line 311
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table66 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table66.AddRow(new string[] {
                        "Facilities for Disabled Guests",
                        "Off"});
#line 312
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table66, "And ");
#line hidden
            TechTalk.SpecFlow.Table table67 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table67.AddRow(new string[] {
                        "Free WiFi",
                        "amount",
                        "On"});
#line 315
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table67, "And ");
#line 318
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table68 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table68.AddRow(new string[] {
                        "Free WiFi",
                        "Off"});
#line 319
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table68, "And ");
#line hidden
            TechTalk.SpecFlow.Table table69 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table69.AddRow(new string[] {
                        "Parking",
                        "amount",
                        "On"});
#line 322
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table69, "And ");
#line 325
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table70 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table70.AddRow(new string[] {
                        "Parking",
                        "Off"});
#line 326
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table70, "And ");
#line hidden
            TechTalk.SpecFlow.Table table71 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table71.AddRow(new string[] {
                        "Spa",
                        "amount",
                        "On"});
#line 329
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table71, "And ");
#line 332
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table72 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table72.AddRow(new string[] {
                        "Spa",
                        "Off"});
#line 333
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table72, "And ");
#line hidden
            TechTalk.SpecFlow.Table table73 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table73.AddRow(new string[] {
                        "Airport Shuttle",
                        "amount",
                        "On"});
#line 336
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table73, "And ");
#line 339
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table74 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table74.AddRow(new string[] {
                        "Airport Shuttle",
                        "Off"});
#line 340
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table74, "And ");
#line hidden
            TechTalk.SpecFlow.Table table75 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table75.AddRow(new string[] {
                        "Swimming Pool",
                        "amount",
                        "On"});
#line 343
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table75, "And ");
#line 346
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table76 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table76.AddRow(new string[] {
                        "Swimming Pool",
                        "Off"});
#line 347
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table76, "And ");
#line hidden
            TechTalk.SpecFlow.Table table77 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table77.AddRow(new string[] {
                        "Air conditioning",
                        "amount",
                        "On"});
#line 350
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table77, "And ");
#line 353
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table78 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table78.AddRow(new string[] {
                        "Air conditioning",
                        "Off"});
#line 354
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table78, "And ");
#line hidden
            TechTalk.SpecFlow.Table table79 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table79.AddRow(new string[] {
                        "Bathtub",
                        "amount",
                        "On"});
#line 357
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table79, "And ");
#line 360
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table80 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table80.AddRow(new string[] {
                        "Bathtub",
                        "Off"});
#line 361
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table80, "And ");
#line hidden
            TechTalk.SpecFlow.Table table81 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table81.AddRow(new string[] {
                        "Coffee machine",
                        "amount",
                        "On"});
#line 364
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table81, "And ");
#line 367
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table82 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table82.AddRow(new string[] {
                        "Coffee machine",
                        "Off"});
#line 368
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table82, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Assurance that Accommodation search filters are working properly together")]
        public virtual void AssuranceThatAccommodationSearchFiltersAreWorkingProperlyTogether()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Assurance that Accommodation search filters are working properly together", ((string[])(null)));
#line 372
this.ScenarioSetup(scenarioInfo);
#line 373
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 374
 testRunner.And("I navigate to url \"https://booking.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 375
 testRunner.And("I set my currency as \"U.S. Dollar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 376
 testRunner.When("I input data \"New York, New York State, USA\" in Destination Search field on main " +
                    "page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 377
 testRunner.And("I click on first autocomplete option that contains \"New York\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 378
 testRunner.And("I set the calendar for the current date plus one year", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 379
 testRunner.Then("I click button Search on main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 380
 testRunner.And("I wait browser page to load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 381
 testRunner.And("I see that I am on Search Result page and see that offered accommodation is in \"N" +
                    "ew York\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table83 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table83.AddRow(new string[] {
                        "US$120 - US$180 per night",
                        "On"});
            table83.AddRow(new string[] {
                        "3 stars",
                        "On"});
            table83.AddRow(new string[] {
                        "Good: 7+",
                        "On"});
            table83.AddRow(new string[] {
                        "Hotels",
                        "On"});
            table83.AddRow(new string[] {
                        "Only show available properties",
                        "On"});
            table83.AddRow(new string[] {
                        "Free WiFi",
                        "On"});
#line 382
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table83, "And ");
#line hidden
            TechTalk.SpecFlow.Table table84 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table84.AddRow(new string[] {
                        "Price",
                        "120 180"});
            table84.AddRow(new string[] {
                        "Stars",
                        "3"});
            table84.AddRow(new string[] {
                        "Rating",
                        "7"});
            table84.AddRow(new string[] {
                        "Free Wifi",
                        "WiFi"});
#line 390
 testRunner.Then("I see that search result contains offers with selected options only", ((string)(null)), table84, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
