// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BookingSpecTests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("AccommodationSearch")]
    public partial class AccommodationSearchFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AccommodationSearch.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "AccommodationSearch", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Input valid data in order to Search accommodation on main page")]
        public virtual void InputValidDataInOrderToSearchAccommodationOnMainPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Input valid data in order to Search accommodation on main page", ((string[])(null)));
#line 3
this.ScenarioSetup(scenarioInfo);
#line 4
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 5
 testRunner.And("I navigate to url \"https://booking.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 6
 testRunner.When("I input data \"New York, New York State, USA\" in Destination Search field on main " +
                    "page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 7
 testRunner.And("I click on first autocomplete option that contains \"New York\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.And("I set the calendar for the current date plus one year", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.Then("I click button Search on main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 10
 testRunner.And("I see that I am on Search Result page and see that offered accommodation is in \"N" +
                    "ew York\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Input invalid data in accommodation search calendar on main page")]
        [NUnit.Framework.TestCaseAttribute("04", "15", "2018", "04", "15", "2020", "Reservations longer than 30 nights are not possible.", null)]
        [NUnit.Framework.TestCaseAttribute("04", "15", "2005", "04", "15", "2005", "Select a check-in date that\'s in the future.", null)]
        public virtual void InputInvalidDataInAccommodationSearchCalendarOnMainPage(string monthIn, string monthDayIn, string yearIn, string monthOut, string monthDayOut, string yearOut, string message, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Input invalid data in accommodation search calendar on main page", exampleTags);
#line 12
this.ScenarioSetup(scenarioInfo);
#line 13
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 14
 testRunner.And("I navigate to url \"https://booking.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Month",
                        "MonthDay",
                        "Year"});
            table1.AddRow(new string[] {
                        "Check In",
                        string.Format("{0}", monthIn),
                        string.Format("{0}", monthDayIn),
                        string.Format("{0}", yearIn)});
            table1.AddRow(new string[] {
                        "Check Out",
                        string.Format("{0}", monthOut),
                        string.Format("{0}", monthDayOut),
                        string.Format("{0}", yearOut)});
#line 15
 testRunner.When("I set following parameters in calendar on main page", ((string)(null)), table1, "When ");
#line 19
 testRunner.When("I input data \"Issaquah, WA, United States\" in Destination Search field on main pa" +
                    "ge", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
 testRunner.And("I click on first autocomplete option that contains \"Issaquah\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
 testRunner.Then("I click button Search on main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 22
 testRunner.And(string.Format("I see date error message \"{0}\" on main page", message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Input invalid data in Destination Search accommodation field on main page")]
        public virtual void InputInvalidDataInDestinationSearchAccommodationFieldOnMainPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Input invalid data in Destination Search accommodation field on main page", ((string[])(null)));
#line 29
 this.ScenarioSetup(scenarioInfo);
#line 30
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 31
 testRunner.And("I navigate to url \"https://booking.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
 testRunner.When("I input data \"sfsadfasdf\" in Destination Search field on main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 33
 testRunner.And("I set the calendar for the current date plus one year", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
 testRunner.Then("I click button Search on main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 35
 testRunner.And("I see destination error message \"Sorry, we don\'t recognize that name.\" on main pa" +
                    "ge", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Check that check-in date always earlier than check-out date")]
        [NUnit.Framework.TestCaseAttribute("04", "25", "2018", "04", "15", "2018", null)]
        [NUnit.Framework.TestCaseAttribute("04", "15", "2018", "04", "13", "2018", null)]
        public virtual void CheckThatCheck_InDateAlwaysEarlierThanCheck_OutDate(string monthIn, string monthDayIn, string yearIn, string monthOut, string monthDayOut, string yearOut, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check that check-in date always earlier than check-out date", exampleTags);
#line 37
this.ScenarioSetup(scenarioInfo);
#line 38
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 39
 testRunner.And("I navigate to url \"https://booking.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Month",
                        "MonthDay",
                        "Year"});
            table2.AddRow(new string[] {
                        "Check In",
                        string.Format("{0}", monthIn),
                        string.Format("{0}", monthDayIn),
                        string.Format("{0}", yearIn)});
            table2.AddRow(new string[] {
                        "Check Out",
                        string.Format("{0}", monthOut),
                        string.Format("{0}", monthDayOut),
                        string.Format("{0}", yearOut)});
#line 40
 testRunner.And("I set following parameters in calendar on main page", ((string)(null)), table2, "And ");
#line 44
 testRunner.Then("I make sure that check-out date is later for one day than check-in", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Check that Search accommodation Adults dropdown menu works properly")]
        public virtual void CheckThatSearchAccommodationAdultsDropdownMenuWorksProperly()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check that Search accommodation Adults dropdown menu works properly", ((string[])(null)));
#line 51
this.ScenarioSetup(scenarioInfo);
#line 52
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 53
 testRunner.And("I navigate to url \"https://booking.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 54
 testRunner.When("I input data \"Issaquah, WA, United States\" in Destination Search field on main pa" +
                    "ge", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 55
 testRunner.And("I click on first autocomplete option that contains \"Issaquah\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 56
 testRunner.And("I set the calendar for the current date plus one year", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table3.AddRow(new string[] {
                        "Adults",
                        "5"});
#line 57
 testRunner.When("I set following parameters in dropdown menus", ((string)(null)), table3, "When ");
#line 60
 testRunner.Then("I click button Search on main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 61
 testRunner.And("I see that Search result is for \"Groups\" and \"5 adults\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Check that Search accommodation Children dropdown menu works properly")]
        public virtual void CheckThatSearchAccommodationChildrenDropdownMenuWorksProperly()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check that Search accommodation Children dropdown menu works properly", ((string[])(null)));
#line 63
 this.ScenarioSetup(scenarioInfo);
#line 64
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 65
 testRunner.And("I navigate to url \"https://booking.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 66
 testRunner.When("I input data \"Issaquah, WA, United States\" in Destination Search field on main pa" +
                    "ge", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 67
 testRunner.And("I click on first autocomplete option that contains \"Issaquah\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 68
 testRunner.And("I set the calendar for the current date plus one year", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table4.AddRow(new string[] {
                        "Children",
                        "1"});
#line 69
 testRunner.When("I set following parameters in dropdown menus", ((string)(null)), table4, "When ");
#line 72
 testRunner.Then("I click button Search on main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 73
 testRunner.And("I see that Search result is for \"Families\" and \"1 child\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Check that Search accommodation Rooms dropdown menu works properly")]
        public virtual void CheckThatSearchAccommodationRoomsDropdownMenuWorksProperly()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check that Search accommodation Rooms dropdown menu works properly", ((string[])(null)));
#line 75
 this.ScenarioSetup(scenarioInfo);
#line 76
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 77
 testRunner.And("I navigate to url \"https://booking.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 78
 testRunner.When("I input data \"Issaquah, WA, United States\" in Destination Search field on main pa" +
                    "ge", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 79
 testRunner.And("I click on first autocomplete option that contains \"Issaquah\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 80
 testRunner.And("I set the calendar for the current date plus one year", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table5.AddRow(new string[] {
                        "Adults",
                        "5"});
            table5.AddRow(new string[] {
                        "Rooms",
                        "3"});
#line 81
 testRunner.When("I set following parameters in dropdown menus", ((string)(null)), table5, "When ");
#line 85
 testRunner.Then("I click button Search on main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 86
 testRunner.And("I see that Search result contains offers with \"3\" rooms", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Check that Search accommodation option Buisness traveling works properly")]
        public virtual void CheckThatSearchAccommodationOptionBuisnessTravelingWorksProperly()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check that Search accommodation option Buisness traveling works properly", ((string[])(null)));
#line 88
this.ScenarioSetup(scenarioInfo);
#line 89
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 90
 testRunner.And("I navigate to url \"https://booking.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 91
 testRunner.When("I input data \"Issaquah, WA, United States\" in Destination Search field on main pa" +
                    "ge", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 92
 testRunner.And("I click on first autocomplete option that contains \"Issaquah\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 93
 testRunner.And("I set the calendar for the current date plus one year", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 94
 testRunner.When("I click Yes for Buisness traveling on main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table6.AddRow(new string[] {
                        "Adults",
                        "3"});
#line 95
 testRunner.When("I set following parameters in dropdown menus", ((string)(null)), table6, "When ");
#line 98
 testRunner.Then("I click button Search on main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 99
 testRunner.And("I see that Search result is for \"Business Travelers\" and \"3 adults\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Assurance that each checkbox filter of Accommodation search works properly")]
        public virtual void AssuranceThatEachCheckboxFilterOfAccommodationSearchWorksProperly()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Assurance that each checkbox filter of Accommodation search works properly", ((string[])(null)));
#line 101
this.ScenarioSetup(scenarioInfo);
#line 102
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 103
 testRunner.And("I navigate to url \"https://booking.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 104
 testRunner.And("I set my currency as \"U.S. Dollar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 105
 testRunner.When("I input data \"New York, New York State, USA\" in Destination Search field on main " +
                    "page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 106
 testRunner.And("I click on first autocomplete option that contains \"New York\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 107
 testRunner.And("I set the calendar for the current date plus one year", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 108
 testRunner.Then("I click button Search on main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 109
 testRunner.And("I wait browser page to load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table7.AddRow(new string[] {
                        "US$61 - US$120 per night",
                        "amount",
                        "On"});
#line 110
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table7, "And ");
#line 113
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table8.AddRow(new string[] {
                        "US$61 - US$120 per night",
                        "Off"});
#line 114
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table8, "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table9.AddRow(new string[] {
                        "US$120 - US$180 per night",
                        "amount",
                        "On"});
#line 117
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table9, "And ");
#line 120
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table10.AddRow(new string[] {
                        "US$120 - US$180 per night",
                        "Off"});
#line 121
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table10, "And ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table11.AddRow(new string[] {
                        "US$180 - US$240 per night",
                        "amount",
                        "On"});
#line 124
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table11, "And ");
#line 127
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table12.AddRow(new string[] {
                        "US$180 - US$240 per night",
                        "Off"});
#line 128
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table12, "And ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table13.AddRow(new string[] {
                        "US$240 + per night",
                        "amount",
                        "On"});
#line 131
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table13, "And ");
#line 134
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table14.AddRow(new string[] {
                        "US$240 + per night",
                        "Off"});
#line 135
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table14, "And ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table15.AddRow(new string[] {
                        "Wonderful: 9+",
                        "amount",
                        "On"});
#line 138
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table15, "And ");
#line 141
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table16.AddRow(new string[] {
                        "Wonderful: 9+",
                        "Off"});
#line 142
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table16, "And ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table17.AddRow(new string[] {
                        "Very Good: 8+",
                        "amount",
                        "On"});
#line 145
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table17, "And ");
#line 148
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table18.AddRow(new string[] {
                        "Very Good: 8+",
                        "Off"});
#line 149
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table18, "And ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table19.AddRow(new string[] {
                        "Good: 7+",
                        "amount",
                        "On"});
#line 152
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table19, "And ");
#line 155
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table20.AddRow(new string[] {
                        "Good: 7+",
                        "Off"});
#line 156
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table20, "And ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table21.AddRow(new string[] {
                        "Pleasant: 6+",
                        "amount",
                        "On"});
#line 159
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table21, "And ");
#line 162
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table22.AddRow(new string[] {
                        "Pleasant: 6+",
                        "Off"});
#line 163
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table22, "And ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table23.AddRow(new string[] {
                        "1 star",
                        "amount",
                        "On"});
#line 166
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table23, "And ");
#line 169
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table24.AddRow(new string[] {
                        "1 star",
                        "Off"});
#line 170
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table24, "And ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table25.AddRow(new string[] {
                        "2 stars",
                        "amount",
                        "On"});
#line 173
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table25, "And ");
#line 176
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table26.AddRow(new string[] {
                        "2 stars",
                        "Off"});
#line 177
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table26, "And ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table27.AddRow(new string[] {
                        "3 stars",
                        "amount",
                        "On"});
#line 180
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table27, "And ");
#line 183
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table28.AddRow(new string[] {
                        "3 stars",
                        "Off"});
#line 184
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table28, "And ");
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table29.AddRow(new string[] {
                        "4 stars",
                        "amount",
                        "On"});
#line 187
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table29, "And ");
#line 190
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table30.AddRow(new string[] {
                        "4 stars",
                        "Off"});
#line 191
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table30, "And ");
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table31.AddRow(new string[] {
                        "5 stars",
                        "amount",
                        "On"});
#line 194
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table31, "And ");
#line 197
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table32.AddRow(new string[] {
                        "5 stars",
                        "Off"});
#line 198
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table32, "And ");
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table33.AddRow(new string[] {
                        "Unrated",
                        "amount",
                        "On"});
#line 201
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table33, "And ");
#line 204
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table34.AddRow(new string[] {
                        "Unrated",
                        "Off"});
#line 205
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table34, "And ");
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table35.AddRow(new string[] {
                        "Front Desk Open 24/7",
                        "amount",
                        "On"});
#line 208
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table35, "And ");
#line 211
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table36.AddRow(new string[] {
                        "Front Desk Open 24/7",
                        "Off"});
#line 212
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table36, "And ");
#line hidden
            TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table37.AddRow(new string[] {
                        "Hotels",
                        "amount",
                        "On"});
#line 215
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table37, "And ");
#line 218
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table38.AddRow(new string[] {
                        "Hotels",
                        "Off"});
#line 219
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table38, "And ");
#line hidden
            TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table39.AddRow(new string[] {
                        "Apartments",
                        "amount",
                        "On"});
#line 222
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table39, "And ");
#line 225
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table40.AddRow(new string[] {
                        "Apartments",
                        "Off"});
#line 226
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table40, "And ");
#line hidden
            TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table41.AddRow(new string[] {
                        "Vacation Homes",
                        "amount",
                        "On"});
#line 229
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table41, "And ");
#line 232
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table42.AddRow(new string[] {
                        "Vacation Homes",
                        "Off"});
#line 233
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table42, "And ");
#line hidden
            TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table43.AddRow(new string[] {
                        "Hostels",
                        "amount",
                        "On"});
#line 236
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table43, "And ");
#line 239
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table44 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table44.AddRow(new string[] {
                        "Hostels",
                        "Off"});
#line 240
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table44, "And ");
#line hidden
            TechTalk.SpecFlow.Table table45 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table45.AddRow(new string[] {
                        "Bed and Breakfasts",
                        "amount",
                        "On"});
#line 243
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table45, "And ");
#line 246
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table46 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table46.AddRow(new string[] {
                        "Bed and Breakfasts",
                        "Off"});
#line 247
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table46, "And ");
#line hidden
            TechTalk.SpecFlow.Table table47 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table47.AddRow(new string[] {
                        "Guesthouses",
                        "amount",
                        "On"});
#line 250
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table47, "And ");
#line 253
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table48 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table48.AddRow(new string[] {
                        "Guesthouses",
                        "Off"});
#line 254
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table48, "And ");
#line hidden
            TechTalk.SpecFlow.Table table49 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table49.AddRow(new string[] {
                        "Homestays",
                        "amount",
                        "On"});
#line 257
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table49, "And ");
#line 260
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table50 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table50.AddRow(new string[] {
                        "Homestays",
                        "Off"});
#line 261
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table50, "And ");
#line hidden
            TechTalk.SpecFlow.Table table51 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table51.AddRow(new string[] {
                        "Family-Friendly Properties",
                        "amount",
                        "On"});
#line 264
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table51, "And ");
#line 267
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table52 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table52.AddRow(new string[] {
                        "Family-Friendly Properties",
                        "Off"});
#line 268
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table52, "And ");
#line hidden
            TechTalk.SpecFlow.Table table53 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table53.AddRow(new string[] {
                        "Fitness Center",
                        "amount",
                        "On"});
#line 271
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table53, "And ");
#line 274
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table54 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table54.AddRow(new string[] {
                        "Fitness Center",
                        "Off"});
#line 275
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table54, "And ");
#line hidden
            TechTalk.SpecFlow.Table table55 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table55.AddRow(new string[] {
                        "Massage",
                        "amount",
                        "On"});
#line 278
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table55, "And ");
#line 281
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table56 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table56.AddRow(new string[] {
                        "Massage",
                        "Off"});
#line 282
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table56, "And ");
#line hidden
            TechTalk.SpecFlow.Table table57 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table57.AddRow(new string[] {
                        "Bicycle Rental (additional charge)",
                        "amount",
                        "On"});
#line 285
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table57, "And ");
#line 288
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table58 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table58.AddRow(new string[] {
                        "Bicycle Rental (additional charge)",
                        "Off"});
#line 289
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table58, "And ");
#line hidden
            TechTalk.SpecFlow.Table table59 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table59.AddRow(new string[] {
                        "Library",
                        "amount",
                        "On"});
#line 292
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table59, "And ");
#line 295
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table60 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table60.AddRow(new string[] {
                        "Library",
                        "Off"});
#line 296
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table60, "And ");
#line hidden
            TechTalk.SpecFlow.Table table61 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table61.AddRow(new string[] {
                        "Fitness",
                        "amount",
                        "On"});
#line 299
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table61, "And ");
#line 302
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table62 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table62.AddRow(new string[] {
                        "Fitness",
                        "Off"});
#line 303
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table62, "And ");
#line hidden
            TechTalk.SpecFlow.Table table63 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table63.AddRow(new string[] {
                        "Great Value Today",
                        "amount",
                        "On"});
#line 306
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table63, "And ");
#line 309
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table64 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table64.AddRow(new string[] {
                        "Great Value Today",
                        "Off"});
#line 310
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table64, "And ");
#line hidden
            TechTalk.SpecFlow.Table table65 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table65.AddRow(new string[] {
                        "Free cancellation",
                        "amount",
                        "On"});
#line 313
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table65, "And ");
#line 316
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table66 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table66.AddRow(new string[] {
                        "Free cancellation",
                        "Off"});
#line 317
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table66, "And ");
#line hidden
            TechTalk.SpecFlow.Table table67 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table67.AddRow(new string[] {
                        "Book without credit card",
                        "amount",
                        "On"});
#line 320
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table67, "And ");
#line 323
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table68 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table68.AddRow(new string[] {
                        "Book without credit card",
                        "Off"});
#line 324
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table68, "And ");
#line hidden
            TechTalk.SpecFlow.Table table69 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table69.AddRow(new string[] {
                        "No prepayment",
                        "amount",
                        "On"});
#line 327
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table69, "And ");
#line 330
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table70 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table70.AddRow(new string[] {
                        "No prepayment",
                        "Off"});
#line 331
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table70, "And ");
#line hidden
            TechTalk.SpecFlow.Table table71 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table71.AddRow(new string[] {
                        "Breakfast included",
                        "amount",
                        "On"});
#line 334
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table71, "And ");
#line 337
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table72 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table72.AddRow(new string[] {
                        "Breakfast included",
                        "Off"});
#line 338
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table72, "And ");
#line hidden
            TechTalk.SpecFlow.Table table73 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table73.AddRow(new string[] {
                        "Great breakfast available",
                        "amount",
                        "On"});
#line 341
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table73, "And ");
#line 344
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table74 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table74.AddRow(new string[] {
                        "Great breakfast available",
                        "Off"});
#line 345
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table74, "And ");
#line hidden
            TechTalk.SpecFlow.Table table75 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table75.AddRow(new string[] {
                        "Kitchen facilities",
                        "amount",
                        "On"});
#line 348
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table75, "And ");
#line 351
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table76 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table76.AddRow(new string[] {
                        "Kitchen facilities",
                        "Off"});
#line 352
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table76, "And ");
#line hidden
            TechTalk.SpecFlow.Table table77 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table77.AddRow(new string[] {
                        "Empire State Building",
                        "amount",
                        "On"});
#line 355
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table77, "And ");
#line 358
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table78 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table78.AddRow(new string[] {
                        "Empire State Building",
                        "Off"});
#line 359
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table78, "And ");
#line hidden
            TechTalk.SpecFlow.Table table79 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table79.AddRow(new string[] {
                        "Times Square",
                        "amount",
                        "On"});
#line 362
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table79, "And ");
#line 365
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table80 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table80.AddRow(new string[] {
                        "Times Square",
                        "Off"});
#line 366
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table80, "And ");
#line hidden
            TechTalk.SpecFlow.Table table81 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table81.AddRow(new string[] {
                        "Brooklyn Bridge",
                        "amount",
                        "On"});
#line 369
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table81, "And ");
#line 372
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table82 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table82.AddRow(new string[] {
                        "Brooklyn Bridge",
                        "Off"});
#line 373
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table82, "And ");
#line hidden
            TechTalk.SpecFlow.Table table83 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table83.AddRow(new string[] {
                        "Central Park",
                        "amount",
                        "On"});
#line 376
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table83, "And ");
#line 379
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table84 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table84.AddRow(new string[] {
                        "Central Park",
                        "Off"});
#line 380
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table84, "And ");
#line hidden
            TechTalk.SpecFlow.Table table85 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table85.AddRow(new string[] {
                        "Top of the Rock",
                        "amount",
                        "On"});
#line 383
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table85, "And ");
#line 386
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table86 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table86.AddRow(new string[] {
                        "Top of the Rock",
                        "Off"});
#line 387
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table86, "And ");
#line hidden
            TechTalk.SpecFlow.Table table87 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table87.AddRow(new string[] {
                        "Twin beds",
                        "amount",
                        "On"});
#line 390
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table87, "And ");
#line 393
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table88 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table88.AddRow(new string[] {
                        "Twin beds",
                        "Off"});
#line 394
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table88, "And ");
#line hidden
            TechTalk.SpecFlow.Table table89 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table89.AddRow(new string[] {
                        "Double bed",
                        "amount",
                        "On"});
#line 397
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table89, "And ");
#line 400
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table90 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table90.AddRow(new string[] {
                        "Double bed",
                        "Off"});
#line 401
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table90, "And ");
#line hidden
            TechTalk.SpecFlow.Table table91 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table91.AddRow(new string[] {
                        "Smoking allowed",
                        "amount",
                        "On"});
#line 404
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table91, "And ");
#line 407
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table92 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table92.AddRow(new string[] {
                        "Smoking allowed",
                        "Off"});
#line 408
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table92, "And ");
#line hidden
            TechTalk.SpecFlow.Table table93 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table93.AddRow(new string[] {
                        "No smoking allowed",
                        "amount",
                        "On"});
#line 411
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table93, "And ");
#line 414
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table94 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table94.AddRow(new string[] {
                        "No smoking allowed",
                        "Off"});
#line 415
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table94, "And ");
#line hidden
            TechTalk.SpecFlow.Table table95 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table95.AddRow(new string[] {
                        "Family Rooms",
                        "amount",
                        "On"});
#line 418
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table95, "And ");
#line 421
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table96 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table96.AddRow(new string[] {
                        "Family Rooms",
                        "Off"});
#line 422
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table96, "And ");
#line hidden
            TechTalk.SpecFlow.Table table97 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table97.AddRow(new string[] {
                        "Pet Friendly",
                        "amount",
                        "On"});
#line 425
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table97, "And ");
#line 428
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table98 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table98.AddRow(new string[] {
                        "Pet Friendly",
                        "Off"});
#line 429
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table98, "And ");
#line hidden
            TechTalk.SpecFlow.Table table99 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table99.AddRow(new string[] {
                        "Facilities for Disabled Guests",
                        "amount",
                        "On"});
#line 432
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table99, "And ");
#line 435
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table100 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table100.AddRow(new string[] {
                        "Facilities for Disabled Guests",
                        "Off"});
#line 436
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table100, "And ");
#line hidden
            TechTalk.SpecFlow.Table table101 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table101.AddRow(new string[] {
                        "Free WiFi",
                        "amount",
                        "On"});
#line 439
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table101, "And ");
#line 442
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table102 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table102.AddRow(new string[] {
                        "Free WiFi",
                        "Off"});
#line 443
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table102, "And ");
#line hidden
            TechTalk.SpecFlow.Table table103 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table103.AddRow(new string[] {
                        "Restaurant",
                        "amount",
                        "On"});
#line 446
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table103, "And ");
#line 449
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table104 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table104.AddRow(new string[] {
                        "Restaurant",
                        "Off"});
#line 450
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table104, "And ");
#line hidden
            TechTalk.SpecFlow.Table table105 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table105.AddRow(new string[] {
                        "Parking",
                        "amount",
                        "On"});
#line 453
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table105, "And ");
#line 456
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table106 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table106.AddRow(new string[] {
                        "Parking",
                        "Off"});
#line 457
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table106, "And ");
#line hidden
            TechTalk.SpecFlow.Table table107 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table107.AddRow(new string[] {
                        "Free Parking",
                        "amount",
                        "On"});
#line 460
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table107, "And ");
#line 463
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table108 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table108.AddRow(new string[] {
                        "Free Parking",
                        "Off"});
#line 464
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table108, "And ");
#line hidden
            TechTalk.SpecFlow.Table table109 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table109.AddRow(new string[] {
                        "Room Service",
                        "amount",
                        "On"});
#line 467
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table109, "And ");
#line 470
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table110 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table110.AddRow(new string[] {
                        "Room Service",
                        "Off"});
#line 471
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table110, "And ");
#line hidden
            TechTalk.SpecFlow.Table table111 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table111.AddRow(new string[] {
                        "Spa",
                        "amount",
                        "On"});
#line 474
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table111, "And ");
#line 477
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table112 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table112.AddRow(new string[] {
                        "Spa",
                        "Off"});
#line 478
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table112, "And ");
#line hidden
            TechTalk.SpecFlow.Table table113 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table113.AddRow(new string[] {
                        "Airport Shuttle",
                        "amount",
                        "On"});
#line 481
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table113, "And ");
#line 484
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table114 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table114.AddRow(new string[] {
                        "Airport Shuttle",
                        "Off"});
#line 485
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table114, "And ");
#line hidden
            TechTalk.SpecFlow.Table table115 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table115.AddRow(new string[] {
                        "Swimming Pool",
                        "amount",
                        "On"});
#line 488
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table115, "And ");
#line 491
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table116 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table116.AddRow(new string[] {
                        "Swimming Pool",
                        "Off"});
#line 492
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table116, "And ");
#line hidden
            TechTalk.SpecFlow.Table table117 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table117.AddRow(new string[] {
                        "Air conditioning",
                        "amount",
                        "On"});
#line 495
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table117, "And ");
#line 498
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table118 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table118.AddRow(new string[] {
                        "Air conditioning",
                        "Off"});
#line 499
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table118, "And ");
#line hidden
            TechTalk.SpecFlow.Table table119 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table119.AddRow(new string[] {
                        "Bathtub",
                        "amount",
                        "On"});
#line 502
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table119, "And ");
#line 505
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table120 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table120.AddRow(new string[] {
                        "Bathtub",
                        "Off"});
#line 506
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table120, "And ");
#line hidden
            TechTalk.SpecFlow.Table table121 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table121.AddRow(new string[] {
                        "Coffee machine",
                        "amount",
                        "On"});
#line 509
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table121, "And ");
#line 512
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table122 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table122.AddRow(new string[] {
                        "Coffee machine",
                        "Off"});
#line 513
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table122, "And ");
#line hidden
            TechTalk.SpecFlow.Table table123 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table123.AddRow(new string[] {
                        "Electric kettle",
                        "amount",
                        "On"});
#line 516
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table123, "And ");
#line 519
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table124 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table124.AddRow(new string[] {
                        "Electric kettle",
                        "Off"});
#line 520
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table124, "And ");
#line hidden
            TechTalk.SpecFlow.Table table125 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Scenario Key",
                        "Value"});
            table125.AddRow(new string[] {
                        "Flat-screen TV",
                        "amount",
                        "On"});
#line 523
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table125, "And ");
#line 526
 testRunner.And("I see that displayed \"amount\" of options equal to amount displayed on filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table126 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table126.AddRow(new string[] {
                        "Flat-screen TV",
                        "Off"});
#line 527
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table126, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Assurance that Accommodation search filters are working properly together")]
        public virtual void AssuranceThatAccommodationSearchFiltersAreWorkingProperlyTogether()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Assurance that Accommodation search filters are working properly together", ((string[])(null)));
#line 531
this.ScenarioSetup(scenarioInfo);
#line 532
 testRunner.When("I open browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 533
 testRunner.And("I navigate to url \"https://booking.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 534
 testRunner.And("I set my currency as \"U.S. Dollar\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 535
 testRunner.When("I input data \"New York, New York State, USA\" in Destination Search field on main " +
                    "page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 536
 testRunner.And("I click on first autocomplete option that contains \"New York\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 537
 testRunner.And("I set the calendar for the current date plus one year", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 538
 testRunner.Then("I click button Search on main page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 539
 testRunner.And("I wait browser page to load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 540
 testRunner.And("I see that I am on Search Result page and see that offered accommodation is in \"N" +
                    "ew York\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table127 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table127.AddRow(new string[] {
                        "US$61 - US$120 per night",
                        "On"});
            table127.AddRow(new string[] {
                        "3 stars",
                        "On"});
            table127.AddRow(new string[] {
                        "Good: 7+",
                        "On"});
            table127.AddRow(new string[] {
                        "Hotels",
                        "On"});
            table127.AddRow(new string[] {
                        "Only show available properties",
                        "On"});
            table127.AddRow(new string[] {
                        "Free WiFi",
                        "On"});
#line 541
 testRunner.And("I set following parameters in filter checkboxes on search result page", ((string)(null)), table127, "And ");
#line hidden
            TechTalk.SpecFlow.Table table128 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table128.AddRow(new string[] {
                        "Price",
                        "61 120"});
            table128.AddRow(new string[] {
                        "Stars",
                        "3"});
            table128.AddRow(new string[] {
                        "Rating",
                        "7"});
            table128.AddRow(new string[] {
                        "Free Wifi",
                        "WiFi"});
#line 549
 testRunner.Then("I see that search result contains offers with selected options only", ((string)(null)), table128, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
